### PR TITLE
a new logo, maybe?

### PR DESCRIPTION
**Pull request by SoilZhu**
as u see

### CODE REVIEW

**Comment by SoilZhu** [comment]
Untitled (Copy) (Copy) (Copy)

**Comment by SimonShiki** [comment]
> Untitled (Copy) (Copy) (Copy)
> 

also https://github.com/EurekaScratch/eureka-loader

**Comment by SoilZhu** [comment]
> > Untitled (Copy) (Copy) (Copy)
> 
> also https://github.com/EurekaScratch/eureka-loader

will u merge this later?

**Comment by SimonShiki** [comment]
> > > Untitled (Copy) (Copy) (Copy)
> > 
> > also https://github.com/EurekaScratch/eureka-loader
> 
> will u merge this later?

need adjust padding, but i have no time now

**Comment by SoilZhu** [comment]
> > > > Untitled (Copy) (Copy) (Copy)
> > > 
> > > 
> > > also https://github.com/EurekaScratch/eureka-loader
> > 
> > 
> > will u merge this later?
> 
> need adjust padding, but i have no time now

image
actually I pushed this pic, not the one in the comment. The pic in the comment is only used to show the design of this logo

**Comment by SoilZhu** [comment]
> > > > > Untitled (Copy) (Copy) (Copy)
> > > > 
> > > > 
> > > > also https://github.com/EurekaScratch/eureka-loader
> > > 
> > > 
> > > will u merge this later?
> > 
> > 
> > need adjust padding, but i have no time now
> 
> image actually I pushed this pic, not the one in the comment. The pic in the comment is only used to show the design of this logo

or told me how to paddy

**Pull request merged**
